#!/usr/bin/env bash
# A script to display information about subdomains

# Get subdomain information
get_subdomain_info() {
	domain=$1
	subdomain=$2'{2:-}'

	if [ -n "$subdomain" ]; then
		record_type=$(dig "$subdomain.$domain" +short | awk '{print $4}')
		destination=$(dig "$subdomain.$domain" +short | awk '{print $5}')
		printf "The subdomain %s is a %s record and points to %s\n" "$subdomain" "$record_type" "$destination"
	else
		for sub in www lb-01 web-01 web-02; do
			record_type=$(dig "$sub.$domain" +short | awk '{print $4}')
			destination=$(dig "$sub.$domain" +short | awk '{print $5}')
			printf "The subdomain %s is a %record and points to %s\n" "$sub" "$record_type" "$destination"
		done
	fi
}

if [ -z "$1" ]; then
	echo "Usage: $0 <domain> [subdomain]"
	exit 1
fi

domain=$1
subdomain=$2'{2:-}'

get_subdomain_info "$domain" "$subdomain"