#!/usr/bin/env bash
# A bash script to install nginx on a server

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

sed -i 's/listen 80 default_server;/listen 80 default_server;\n\tlocation \/ {\n\t\troot \/var/www/html;\n\t\tindex index.html;\n\t}/' /etc/nginx/sites-available/default

nginx -s reload

nginx -t
