#!/usr/bin/env bash
# A bash script to install nginx on a server

sudo apt-get update

sudo apt-get install -y nginx

# Start nginx server
sudo service nginx start

# enable firewall
sudo ufw allow 'Nginx HTTP'

sudo ufw enabled

# Give ownership permission to files
sudo chown -R "$USER":$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup index file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create the index file
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restart nginx server
sudo service nginx restart
