#!/usr/bin/env bash
# Script to double the number of webservers

# install nginx
sudo apt-get update ;
sudo apt-get -y install nginx

string="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$string/" /etc/nginx/nginx.conf

sudo service nginx restart