#!/usr/bin/env bash
# # A script to change port in nginx
# sed -i 's/listen [0-9]*;/listen 80 default_server;/' /etc/nginx/sites-available/default
# sudo service nginx restart

new="80 default_server"
old="8080 default_server"
sed -i "s/$old/$new/" /etc/nginx/sites-enabled/default

service nginx restart
